on:
  push:
    branches:
    - master
    
jobs:
  deploy-layers:
    name: deploy Layers to AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Installing Serverless@2
      run: npm install serverless@2 -g
    - name: Installing Typescript
      run: npm install typescript -g
    - name: Installing Dependecies
      working-directory: ./layers/utilities/nodejs/node_modules/utilities
      run: |
        npm i
        tsc
    - name: Deploying
      working-directory: ./layers
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        serverless deploy

  deploy-service:
    needs: deploy-layers
    name: deploy Service to AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Installing Serverless@2
      run: npm install serverless@2 -g
    - name: Installing Typescript
      run: npm install typescript -g
    - name: Installing Dependecies
      working-directory: ./api
      run: |
        npm i
    - name: Deploying
      working-directory: ./api
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        serverless deploy
        
