on:
  push:
    branches:
    - master
    
jobs:
  my_job:
    name: deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install, build and test
      run: |
        export AWS_ACCESS_KEY_ID=$AWS_KEY
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET
        npm install serverless@2 -g
        npm ci
        serverless deploy
        
